import type {Metadata} from "next";
import {Roboto} from "next/font/google";
import "./globals.css";
import "./prismjs.css";
import "./notion.css";
import React from "react";
import {ThemeProvider} from "@/helpers/ThemeContext";


const roboto = Roboto({
    weight: ["100", "300", "400", "500", "700"],
    subsets: ['latin']
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body className={roboto.className}>
        <ThemeProvider>
            {children}
        </ThemeProvider>
        </body>
        </html>
    );
}
